// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzx7MDawLmRGLdRNhXfqXZy7-VlY5VKM',
    appId: '1:486292451670:web:1a369563a934cab4c6e6f7',
    messagingSenderId: '486292451670',
    projectId: 'farm-310bf',
    authDomain: 'farm-310bf.firebaseapp.com',
    databaseURL: 'https://farm-310bf-default-rtdb.firebaseio.com',
    storageBucket: 'farm-310bf.firebasestorage.app',
    measurementId: 'G-Y41MPKMY2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7f4rDPLFnNE2hWtCZbj08bEQUwXhWSRw',
    appId: '1:486292451670:android:3369dc48911be303c6e6f7',
    messagingSenderId: '486292451670',
    projectId: 'farm-310bf',
    databaseURL: 'https://farm-310bf-default-rtdb.firebaseio.com',
    storageBucket: 'farm-310bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNVQUm8VKZxgTwPZJcDgTnkPhsmOLO0Y',
    appId: '1:486292451670:ios:77f0990a5fcc763dc6e6f7',
    messagingSenderId: '486292451670',
    projectId: 'farm-310bf',
    databaseURL: 'https://farm-310bf-default-rtdb.firebaseio.com',
    storageBucket: 'farm-310bf.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNVQUm8VKZxgTwPZJcDgTnkPhsmOLO0Y',
    appId: '1:486292451670:ios:77f0990a5fcc763dc6e6f7',
    messagingSenderId: '486292451670',
    projectId: 'farm-310bf',
    databaseURL: 'https://farm-310bf-default-rtdb.firebaseio.com',
    storageBucket: 'farm-310bf.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgzx7MDawLmRGLdRNhXfqXZy7-VlY5VKM',
    appId: '1:486292451670:web:fb1ffed542675a63c6e6f7',
    messagingSenderId: '486292451670',
    projectId: 'farm-310bf',
    authDomain: 'farm-310bf.firebaseapp.com',
    databaseURL: 'https://farm-310bf-default-rtdb.firebaseio.com',
    storageBucket: 'farm-310bf.firebasestorage.app',
    measurementId: 'G-LXV22Y33J9',
  );
}
